### ISSUE TITLE
Add library collection

### ISSUE THREAD

**Issue by caiopiccirillo** [LLagu/HAL-controller-test#3]
There's a lot of library collection that we could use, such as:

- [Abseil](https://abseil.io) - Google
- [Poco](https://pocoproject.org/)
- [Boost](https://www.boost.org/)
- [Folly](https://github.com/facebook/folly) - Facebook

Please, share your thoughts which one you'd like to work with. Then, we need to integrate with our build system.
These libraries are super helpful when we need some algorithm, file manipulation or any functionality we need to add and they're lightyears ahead in development and pretty well tested.

**Comment by LLagu** [comment]
I am considering either Abseil or Boost. From what I can gather online POCO is centered on network-centric application and Folly, well, I just have a repulsion towards anything Facebook/Meta.

With the premise that I never used any of those libraries, looks like that the main reasons to go for Abseil is API stability and compatibility over time (might not be relevant for our project) and performance (could be important depending on which microcontroller we'll end up using) while Boost offers more cutting edge features but it's more "unstable".

Having said that if you have experience in any of those it might be good to simply go for that one for the sake of time efficiency.

**Comment by caiopiccirillo** [comment]
> I am considering either Abseil or Boost. From what I can gather online POCO is centered on network-centric application and Folly, well, I just have a repulsion towards anything Facebook/Meta.
> 
> With the premise that I never used any of those libraries, looks like that the main reasons to go for Abseil is API stability and compatibility over time (might not be relevant for our project) and performance (could be important depending on which microcontroller we'll end up using) while Boost offers more cutting edge features but it's more "unstable".
> 
> Having said that if you have experience in any of those it might be good to simply go for that one for the sake of time efficiency.

I'm inclined to use Abseil, just because I'm curious how it is easy to use haha.
You could take a look how I integrated GTest in `test/CMakeLists.txt` and use as example, then use method [absl::StrSplit()](https://abseil.io/docs/cpp/guides/strings#abslstrsplit-for-splitting-strings) in main to check if it compiles and run without a problem.

**Comment by LLagu** [comment]
Sounds good, let's try Abseil then!
